/* Internal binary handles for restart types (R_ : read, W_ : write) */
# define R_KS      1
# define W_KS      2
# define R_cor     4
# define W_cor     8
# define R_cot     4
# define W_cot     8
# define R_ccou    4
# define W_ccou    8
# define R_mbas    4
# define W_mbas    8
# define R_core    4
# define R_sigx   16
# define W_sigx   32
# define R_sigc   64
# define W_sigc  128
# define R_sigt   64
# define W_sigt  128
# define R_wcou   64
# define W_wcou  128
# define R_spec   64
# define R_uwan  256
# define W_uwan  512
# define R_kolap 256
# define W_kolap 512
